import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import ProfileSideBar from "@/components/common/ProfileSideBar";
import Header from "@/components/common/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-background !min-h-screen antialiased`}
      >
        <div className="relative">
          <Header />
          <div className="max-w-[1512px] mx-auto overflow-hidden 2xl:flex-row flex-col flex items-center justify-between w-full h-full gap-[52px] px-5">
            <ProfileSideBar />
            {children}
            <NavBar />
          </div>
        </div>
      </body>
    </html>
  );
}
